services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PYTHONPATH=/app
      - PYTHONPYCACHEPREFIX=""
      - PYTHONDONTWRITEBYTECODE=1
      - DEBUG=false
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000