services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app   
      - PYTHONPYCACHEPREFIX=/app/__pycache__
      - DEBUG=true
    volumes:
      - .:/app
    # (main:) refers to the main.py – (app) refers to the app variable in the main.py file
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload